### PR TITLE
Mega Evolution occurs after switching

### PR DESCRIPTION
**Pull request by VeteranPadgett**
This change keeps priority from before mega evolved. Need to test something like Mega Sableye in game to see if it has priority or not.

### CODE REVIEW

**Comment by VeteranPadgett** [comment]
Am told that the mega evolution's ability is used for turn order. Made another commit to reflect this.

**Comment by coyotte508** [comment]
This is a dangerous change, we already had pains making sure the turn order and everything was correct for mega evos in gen 7 because of how different it is from gen 6.

And if the change is actually as your commits imply, then a simple three lines suffice:

```cpp
if (gen() >= 7) {
    playersByOrder = sortedBySpeed();
}
```

Instead of moving the whole block. So make sure w/ Fuzzy that the different scenario are still correct. For example with your commit speed for **everyone** is recalculated **after** switching, so a pokemon with swift swim will suddenly gain speed if a pokemon with rain dance is switched in, and attack first that turn.

**Comment by VeteranPadgett** [comment]
I thought that swift swim was supposed to affect speed though. I'll test it in game myself when I can then. There's a bunch of special cases if it uses the original weather.

**Comment by coyotte508** [comment]
No, there's not... As long as the mechanics is properly understood, it can be coded cleanly, without special cases.

**Comment by turbedi** [comment]
What's the status of this PR?

**Comment by coyotte508** [comment]
Just need to know what is the actual behavior, properly described. Do we use the speed of mega'd pokemon after their mega evo, or before? 

If we use the speed before, then no change is needed in speed calculation, we can just use the same code as pre-gen-7.

If we use the speed after, that means that we recalculate the speed of mega evo'd pokemon after they evolved. Do we recalculate the speed of **other** pokemon after switches occurred too? That opens the way for speed-boosting weather-pokes giving their partner a speed boost the turn they're switched in, a new kind of strategy. For example a pokemon with `Swift Swim` would see his speed boosted if a pokemon with rain dance switched in, which does not happen to my knowledge in gen 6- (only for subsequent turns). Anyway, if that is the case, then the three lines in my previous comment are enough.

If we use the speed after switches, but only the speed of **newly evolved megas** are recalculated, then we need to move the priority thing after switches. In that case we need to make sure `Analyic` + `Pursuit` doesn't crash the game. We also need to keep the original speeds vector (before switches, or before mega  evos, w/e), and only recalculate speeds for mega evos. This code is already here, some things just need to be moved.

If we only use priority effects of mega abilities, and not new speeds, then we need to move the priority calculation after mega evos. Make sure that `Analytic` + `Pursuit` doesn't crash... And same as above.

In any case, the expected behavior needs to be detailed, with a few examples, to make sure that if we do any future change we'll still follow those few examples and not break anything.

**Comment by CTCC1** [comment]
http://pokemon-online.eu/threads/35422/#post-488804
I posted on the forum quite some time ago about this issue: "In double battle, if rain is up and Charizard mega evolves into Mega Charizard-Y and Drought activates, Swift Swimmers still have the boost and attack first." However, if Sableye Mega evolved that turn, it does not receive Prankster boost; in addition, Banette on the turn of Mega evolution receives Prankster boost, Mega Alakazam Tracing a swift swimmer immediately outspeeds that turn.
To conclude, We use the speed/ability-related-speed/priority-boost of mega evolved pokemons after their mega evo, and this does not affect the speed/speed boost of Other pokemon on the field.

**Comment by coyotte508** [comment]
Thank you @CTCC1 , I opened #1593 with that info in mind

**Pull request closed without merging**
