### PR TITLE
Illegal gen 1 movesets

### PR DESCRIPTION
**Pull request by VeteranPadgett**
https://github.com/po-devs/po-server-goodies/pull/834

### CODE REVIEW

**Comment by turbedi** [comment]
Travis is complaining, but it builds fine for me and works.

**Comment by Fuzzysqurl** [comment]
```movesetchecker.cpp: In static member function ‘static bool MoveSetChecker::isValid(const Pokemon::uniqueId&, Pokemon::gen, const QSet<int>&, int, int, int, bool, QSet<int>*, QString*, int)’:

movesetchecker.cpp:302:347: error: could not convert ‘{{"Kakuna", {{"Harden", {"Poison Sting", "String Shot"}}}}, {"Beedrill", {{"Harden", {"Poison Sting", "String Shot"}}}}, {"Fearow", {{"Payday", {"Peck"}}}}, {"Nidoking", {{"Thrash", {"Fury Attack"}}}}, {"Rapidash", {{"Pay Day", {"Tail Whip", "Growl"}}}}, {"Exeggutor", {{"Stomp", {"Sleep Powder", "Stun Spore", "Poison Powder"}}}}, {"Fearow", {{"Pay Day", {"Peck"}}}}, {"Jolteon", {{"Focus Energy", {"Thunder Shock"}}}}, {"Flareon", {{"Focus Energy", {"Ember"}}}}, {"Mewtwo", {{"Confusion", <brace-enclosed initializer list>()}, {"Disable", <brace-enclosed initializer list>()}}}}’ from ‘<brace-enclosed initializer list>’ to ‘const QHash<QString, QHash<QString, QList<QString> > >’```

**Comment by VeteranPadgett** [comment]
It would just make the statement twice as long, but it already should work.

**Comment by VeteranPadgett** [comment]
Also, not a problem, but I just realized I listed Fearow twice lol.

**Comment by turbedi** [comment]
Do the brackets after Confusion and Disable cause the issue? And are there really needed? ( I have no idea, but these brackets aren't used anywhere else)

**Comment by VeteranPadgett** [comment]
Those are empty, because Mewtwo doesn't learn Confusion or Disable regardless of what other moves it learns. You can see on line 306 that it checks if that list is empty. If it is then the move is illegal. Otherwise, it checks if the Pokemon also has one of the moves in the list.

**Comment by turbedi** [comment]
Ah okay. I was curious because it seems that Travis is complaining because of these brackets (if I understood it correctly)

**Comment by Fuzzysqurl** [comment]
Ok what am I doing wrong that I can't test it? http://i.imgur.com/cmQWwf9.png

**Comment by turbedi** [comment]
No idea, it works fine for me :|

**Comment by CrystalMoogle** [comment]
Doesn't work for me either btw

**Comment by turbedi** [comment]
Strange..

**Comment by CrystalMoogle** [comment]
Does it actually work in the Teambuilder for you too?

**Comment by turbedi** [comment]
Yes, it does.

**Comment by VeteranPadgett** [comment]
Can someone that this doesn't already work for try this:

Remove "const", see if it works. If not, see if it complains about any of these statements in a build:

QHash<QString, QString> a = {{"a", "b"}, {"c", "d"}};
QList<QString> b = {"a", "b"}
QList<QString> c = {};

**Comment by turbedi** [comment]
It still works for me, but I noticed anoter thing: 
I am not able to give Mewtwo Confusion or Disable at all.

**Comment by CrystalMoogle** [comment]
Needs template argument for qhash

**Comment by VeteranPadgett** [comment]
Oh, forgot about setting the type. Try adding <QString> like this:

QHash<QString, QString> a = {{"a", "b"}, {"c", "d"}};
QList<QString> b = {"a", "b"};
QList<QString> c = {};

**Comment by VeteranPadgett** [comment]
wtf

**Comment by CrystalMoogle** [comment]
error: could not convert '{{"a", "b"}, {"c", "d"}}' from '<brace-enclosed initializer list>' to 'QHash<QString, QString>'

**Comment by CrystalMoogle** [comment]
I get no error when building in Qt5.3, but I do in Qt5. Unfortunately we
kinda have to use Qt5 due to the new battle window...

**Comment by Fuzzysqurl** [comment]
Just going to point out, we could theoretically reuse a majority of this fix (when it works for QT5) for event move + ability combinations (such as Japanese Sticker Pokemon or the new Unova HA Pokemon) and dump those from the scripts.

Instead of ```Pokemon, Move, Moves``` it would be ```Pokemon, Ability, Moves```

**Comment by VeteranPadgett** [comment]
Does anyone know how to define a QHash in Qt5? If so, I can do that otherwise I'll just use the QHash insert function.

**Comment by VeteranPadgett** [comment]
nvm I figured out the problem. You have to put spaces between the closing angle brackets or the compiler can misinterpret it as a right shift.

**Comment by VeteranPadgett** [comment]
About Mewtwo, it was my understanding from the thread that Mewtwo learns Confusion and Disable but at a lower level than he can be obtained.

**Comment by VeteranPadgett** [comment]
Still failed travis ci :(

**Comment by jinorae** [comment]
maybe qt4 doesn't support initializer list syntax?
travis logs say it's using qt4 to compile

**Comment by CrystalMoogle** [comment]
Me and Fuzzy used qt5.0.2, although it's possible only later versions of
qt5 support it. Unfortunately, we can't use them due to the new battle
window...

**Comment by VeteranPadgett** [comment]
Did it the long way.

**Comment by Fuzzysqurl** [comment]
squish pls? :]

**Comment by VeteranPadgett** [comment]
Squishy squishy

For the Mewtwo moves, would it be better to just remove Confusion and Disable from the database except for the tradebacks subgen? It's kinda weird to have the moves in the Teambuilder, but you can't use them at all.

**Pull request merged**
