### PR TITLE
Some UI changes

### PR DESCRIPTION
**Pull request by turbedi**
- Remove the option to disable Advanced tab in teambuilder
- Update credits.html
- Rework the About tab in menu bar (renamed to Help). More tabs coming soon, design suggestions appreciated. Some pictures:
http://puu.sh/om2wi.png
http://puu.sh/om2xs.png
I'm gonna let you merge this @Fuzzysqurl , because I don't now if you agree with the changes.

### CODE REVIEW

**Comment by Fuzzysqurl** [comment]
Why not make credits pull from PO-server-goodies? Similar to registry notice pulling

**Comment by turbedi** [comment]
Then the formatting and the "Special Thanks" part will be lost. And the contributors-list is kinda troll ((23:48:46) Hikari's contributions: Idk, pick one - Weavile)

**Comment by Fuzzysqurl** [comment]
I meant make it so we can change the credits without a client update

**Comment by Fuzzysqurl** [comment]
Also we took smogons sprites technically. They compressed the sprites and altered some colors to make them smaller.

**Comment by turbedi** [comment]
Gonna try to change this tomorrow, I don't have time to do it right now

**Comment by turbedi** [comment]
Done

**Comment by turbedi** [comment]
After submitting thousands of commits i realized that this PR breaks the buildbot :/

**Pull request merged**
