### PR TITLE
Fix Confusion damage with substitute

### PR DESCRIPTION
**Pull request by turbedi**
http://pokemon-online.eu/threads/substitute-and-confusion.31373/#post-440847

I hope that everything is correct. ^^'
And is there a reason why it is "gen() <=1" and not "gen() == 1", or can i change it?

### CODE REVIEW

**Comment by turbedi** [comment]
I squashed the commits and did a quick testing. It seems to work

**Comment by CrystalMoogle** [comment]
You'd have to use .num to get gen() == 1 iirc. I once did it before and it doesn't work because gen() returns .num and .subnum or something

**Comment by turbedi** [comment]
Done. Should I also change the "gen() <= 1" in line 1927?

**Comment by turbedi** [comment]
:question:

**Pull request merged**
