### PR TITLE
Fix Present in Gen 2 (not tested yet)

### PR DESCRIPTION
**Pull request by turbedi**
Got the information from here:
http://bulbapedia.bulbagarden.net/wiki/Present_(move)#Generation_II

Gonna test this PR soon. I've already opened the PR so that someone else can look into the code and tell me if I messed up something

### CODE REVIEW

**Comment by sulcata** [comment]
The if-else code looks a bit spaghetti-ish, but it seems like it should probably be correct (maybe?). An array of values accessed by the integer value of the type would probably make it more clear as to what is going on.

Also adding in braces for multiline conditionals would be the best practice in general to avoid accidental bugs.

**Comment by Fuzzysqurl** [comment]
Also you just changed it for gens 3-7 too. 

Do gen() < stadium2 or something. Present doesn't exist in gen 1

**Comment by sulcata** [comment]
Something like this btw (no idea if this compiles haven't touched C++ in a while):
```
int typeConversions[] = {1, 2, 3, 4, 5, 7, 8, 9, 20, 21, 22, 23, 24, 25, 26, 27};
attack = 10;
def = typeConversions[getType(p, 2)];
level = typeConversions[getType(t, 2)];
```

**Comment by turbedi** [comment]
@Fuzzysqurl Line 3124 already checks for Gen == 2, so it should be fine

**Comment by turbedi** [comment]
@Fuzzysqurl [Line 3124](https://github.com/turbedi/pokemon-online/blob/6e7195fbb3316a471b2cb7537cdeb471b8a9f522/src/BattleServer/battle.cpp#L3124) already checks for Gen 2, so it should be fine.
@sulcata Your approach with the array looks much cleaner, I will try to do it this way.

**Comment by Fuzzysqurl** [comment]
Ah. Couldn't see on mobile

**Comment by turbedi** [comment]
@sulcata I've copied your code and it seems to compile.
 Merge or test it first?
I am not able to test it right now, because everytime I start the server I get an error message saying that Battle Server couldn't start bla bla and no idea how to fix it :v

**Comment by turbedi** [comment]
Still not able to test my PRs, but it should work fine. Merge?

**Pull request merged**
