### PR TITLE
Update to 2.7.2

### PR DESCRIPTION
**Pull request by VeteranPadgett**

### CODE REVIEW

**Comment by turbedi** [comment]
I'm gonna merge this PR on Sunday because I don't have time to build the new client before then. (Same for the Android PR)

**Comment by CTCC1** [comment]
http://pokemon-online.eu/threads/35655/  Can we at least have the terrain message thingy (any language) fixed on droid b4 we update it to 2.7.2 for droid?

**Comment by turbedi** [comment]
I tried to fix it some days ago, but the way terrain messages are coded right now is a complete mess, so I am not sure if I will be able to do that :c

**Comment by CTCC1** [comment]
yeah ik, Windows client call terrain message out from another place, and droid doesn't do it that way...rip...GL i guess 0.0

**Pull request merged**
