### PR TITLE
Should fix Color Change + Doom Desire

### PR DESCRIPTION
**Pull request by coyotte508**

### CODE REVIEW

**Comment by turbedi** [comment]
https://puu.sh/syfqN.png
Still not working correctly

**Comment by coyotte508** [comment]
Should work now. Ugh...

**Comment by turbedi** [comment]
I forgot about this PR, sorry :x
Should I still test it or did you already do it?

**Comment by coyotte508** [comment]
Please test! I'll do it tonight otherwise.

**Comment by turbedi** [comment]
Tested, everything is working fine now ~

**Pull request merged**
