### PR TITLE
Rocky Helmet + Disguise and Shell Trap

### PR DESCRIPTION
**Pull request by VeteranPadgett**

### CODE REVIEW

**Comment by VeteranPadgett** [comment]
Setting the power to 0 didn't work because Poison types should still take resisted damage, so I added a Corrosion check for damaging moves when against an immune type. No need for AMCorrosion after that so I just removed it.

**Comment by coyotte508** [comment]
It has conflicts with abilities.cpp, I can't merge.

**Comment by VeteranPadgett** [comment]
Can you merge --theirs, or should I make a dummy Corrosion structure?

**Comment by coyotte508** [comment]
Well what you'd go is `git pull --rebase` to pull the changes from the main repo, and apply your commits on top of it. Then you'd see the conficts, fix them with git. 

But I'm gonna fix it.

**Pull request merged**
