### PR TITLE
Fix Perish Song + Tie break

### PR DESCRIPTION
**Pull request by turbedi**
I tested it quickly and it seems to work as intended after removing this line.
http://pokemon-online.eu/threads/perish-song-tiebreak.32286/#post-450418

### CODE REVIEW

**Comment by coyotte508** [comment]
No, this is gen-dependent. You'll fix the bug for last gen but for gen 4 I think this is the correct behavior.

**Comment by turbedi** [comment]
Should I ask for ingame tests in the post or should I just add a check for gen 4? 
And what about the other gens?

**Comment by coyotte508** [comment]
Maybe just add a if (b.gen() <= 4), and that'd be enough

**Comment by turbedi** [comment]
Fixed it, but I can't rebase it to remove the new commit because after the last big update of my GitHub client everything is messed up :/
Will try to fix everything tomorrow, I am too tired right now.. :sleeping:

**Comment by coyotte508** [comment]
ok, also add a comment explaining stuff and braces with the if :)

Good night!

**Comment by turbedi** [comment]
Added a comment and squashed the commits

**Pull request merged**
