### PR TITLE
Mega Preset in Teambuilder

### PR DESCRIPTION
**Pull request by Fuzzysqurl**
- Adds a drop down menu to select a mega in the teambuilder, similar to arceus/giratina-o. 
- It automatically gives the correct mega stone to the pokemon and even displays its typing/stats/ability. (the pokemon sent to battle will obviously be the non-mega'd version)
- If you remove the mega stone, the pokemon reverts back to its base form.
- If you give a pokemon their correct mega stone, nothing happens (just in case someone doesnt want it to show the new form)

in gif form: http://i.imgur.com/OlurZqO.gif

### CODE REVIEW

**Comment by CrystalMoogle** [comment]
That's really just gonna confuse people on why you can't start with the mega... The teambuilder should try to reflect what the battle will start with.

**Comment by Fuzzysqurl** [comment]
One reason I didn't commit directly.
What about changing the drop down to just give the correct item and if they find the Mega Pokemon through advanced search to use this behavior?

**Comment by CrystalMoogle** [comment]
That works. Although Groudon/Kyogre can auto transform in teambuilder, since I don't think there's any way to prevent them changing.

**Comment by Fuzzysqurl** [comment]
I'll squish it to one commit before merging, but there's no way to use Megas in some cases but not others. 
As far as groudon/kyogre go, I can add a small check into the 2nd commit to see if the pokemon is Groudon or Kyogre, then skip it (allowing the primals to be used in the TB), otherwise its all consistent. You can still search for the mega, see its stats in the search, but the actual building part will only change the item.

**Comment by CrystalMoogle** [comment]
Well it's not like the primal thing is important. It can have the same mechanics as mega, which is the most "accurate" way of doing things.

**Pull request merged**
