### PR TITLE
Battle factory doesn't change the players teams

### PR DESCRIPTION
**Pull request by VeteranPadgett**
Instead of changing the player's team, it changes a copy of the player's team which is the team used in battles. Made it so that the script functions can change a team by reference, but they still support changing the player's team using the slot number if needed. 100 is an arbitrary number, but the point is that the client only lets the player have six teams, and memory addresses that low aren't going to be allocated.

This does mess up the /showteam command for Battle Factory though :(. If you want that to work with this the command would have to get the team from the battle server.

### CODE REVIEW

**Comment by CrystalMoogle** [comment]
This fails to build according to Travis

Also can you explain a bit more on how this works? How does it fix the bug it's meant to be fixing exactly?

**Comment by CrystalMoogle** [comment]
Ok I tested this, every seems ok (although teams with no pokemon don't seem to revert, but that's a non-issue, really)

**Comment by Fuzzysqurl** [comment]
99% of the time Travis doesn't even bother returning a pass/fail for me. There's more than a handful of pulls that were merged by Coyo that "failed" despite not ever causing issues.

**Comment by VeteranPadgett** [comment]
Ah, I think it failed because it wants 64 bit pointers. That could actually be a problem, though I've yet to see the copy team get an address that large. Here's a change to make it use 64 bits, though it might still fail Travis CI cause I had to split it into two 32 bit ints in order to send it to pass the address to the script lol.

**Comment by VeteranPadgett** [comment]
Make sure to get the scripts part of this as well.

**Comment by CrystalMoogle** [comment]
Yeah I know, but I'm leaving that until server update.

**Pull request merged**
