### PR TITLE
Fix last damage variable resetting in Stadium

### PR DESCRIPTION
**Pull request by turbedi**
The variable storing the last damage dealt is properly set to 0 when
needed (after a full paralysis, a switch, a charge turn...) in Stadium.
Did a quick test and seems to work fine

### CODE REVIEW

**Comment by coyotte508** [comment]
Why change battlebase.h ?

Those changes would mean to not forget recompiling any BattleServer plugins when updating po server, otherwise they would break.

**Comment by Fuzzysqurl** [comment]
I have a different concern: it looks like something completely new added, so where does it get changed/accessed when the damage is > 0? I don't have the code in an easy to view format right now so sorry if it's obvious.

**Comment by turbedi** [comment]
I had to change battlebase.h, because otherwise I got a "battleMemory was not defined" error during compilation IIRC. I wasn't sure either if this change is ideal. That's why I didn't merge the PR on my own but waited for a review ^^'

**Comment by coyotte508** [comment]
@turbedi then you need to create the corresponding functions in `BattleRBY`, that also call their main function in `BattleBase`. Like the functions for `sendBack` and `testStatus` of `battle.cpp` call their main function.

Actually I think you can make `testStatus` pure virtual and move it all in `BattleRBY` as the one in `battle.cpp` doesn't call it.

RBY code should be in `BattleRBY` anyway...

**Comment by turbedi** [comment]
I'm gonna change this tomorrow then, I am way too tired right now :x

**Comment by turbedi** [comment]
Updated the PR (10 days too late, whoops).
I have no idea if I did it correctly. All I know is that it compiles

**Comment by coyotte508** [comment]
don't remove `testStatus`, make it pure virtual in the header if you need. Just don't remove/add functions in `battlebase.h` unless it's a PO version change.

**Comment by turbedi** [comment]
Added testStatus back in battlebase.cpp and made it pure virtual in battlebase.h (I think?)

**Pull request merged**
