### PR TITLE
Use movemachine

### PR DESCRIPTION
**Pull request by VeteranPadgett**
Ran movemachine because I noticed none of the breeding moves were added to the evolutions' preevo moves. Turns out there were other problems too.

egg_moves and level_moves: removed a bunch of duplicate moves
preevo_moves: added new breeding moves and removed moves that the preevo learned from 6G tutor

The rest was removing/adding some forms from the list.

### CODE REVIEW

**Comment by turbedi** [comment]
This removes all the duplicate move entries, right?

**Comment by VeteranPadgett** [comment]
Hang on, double checking the form removals

**Comment by VeteranPadgett** [comment]
Yes

**Comment by VeteranPadgett** [comment]
Ok this should be good to go.

**Pull request merged**
