### PR TITLE
Fix Metal Burst

### PR DESCRIPTION
**Pull request by turbedi**
http://pokemon-online.eu/threads/metal-burst.29998/#post-422916

### CODE REVIEW

**Comment by CrystalMoogle** [comment]
You need to start using git pull on the main repo before you make commits...

**Comment by turbedi** [comment]
I have no idea how to use git pull :|

**Comment by CrystalMoogle** [comment]
You know how to rebase but not git pull. What.
It's "git pull https://github.com/po-devs/pokemon-online.git master"
Or set https://github.com/po-devs/pokemon-online.git as a remote using "git
remote add https://github.com/po-devs/pokemon-online.git upstream"
Then do, git pull upstream master

**Comment by turbedi** [comment]
I messed up something. o.o

**Comment by CrystalMoogle** [comment]
Yeah it's kinda too late to git pull now, which is why I said you need to
start doing it before you commit. The reason being is because this commit
can't be merged due to a merge conflict, which happens when using outdated
copy.
You'll probably need to scrap this commit and do it all over again.

**Pull request closed without merging**
