### PR TITLE
Fix PP of Mimic'd move in Stadium

### PR DESCRIPTION
**Pull request by turbedi**

### CODE REVIEW

**Comment by coyotte508** [comment]
Is it 15 even for moves with lower PPs?

**Comment by turbedi** [comment]
Asked about it in the forum thread. Gonna change it once he replies

**Comment by turbedi** [comment]
Nevermind, looks like it is also 15 for moves with lover PP. 
http://pokemon-online.eu/threads/stadium-checklist.33832/#post-466239
He took Blizzard as an example and it is the same

**Comment by Guernouille** [comment]
The max PP should be 10, on this screenshot the PPs are at 16 because of PP Ups.

**Comment by turbedi** [comment]
But it is 16 with PP Max, isn't it? So after using Mimic the PP is 15, or am I wrong?

**Comment by Fuzzysqurl** [comment]
I don't follow the reasoning for the response on coyo's question. 

What if you mimicked something with 8 max PP? Would you be given 15?
What if you mimicked something with 64 max PP? Would you be given 15?

**Comment by Guernouille** [comment]
You use Mimic, you copy Tackle. PP is 15/16.
You use the mimicked Tackle, PP is 14/16.
You switch out, then later switch back to the Pokémon with Mimic. Mimic's PP is 14/16.

**Comment by coyotte508** [comment]
Maximum PP is not that relevant, as PPs can't be gained back in stadium or RBY (although it *is* something, it's very little).

The client's battle window will probably show something like 15/8 for Blizzard, instead of 15/16. But it doesn't affect battle itself.

Actually for the client it's easily fixed, the PP max just has to never change even if the move changes, for RBY battles. It doesn't impact on server code.

**Comment by coyotte508** [comment]
https://github.com/po-devs/pokemon-online/commit/62077ee4c2635b1984cd6e3619db9f7e2d4c55f4 will fix the issue mentioned by @Guernouille for the client.

**Comment by Guernouille** [comment]
It just has an importance in RBY (Mimic goes at 63 PP if it copies Wrap / Bind / Fire Spin / Clamp, and it uses its last PP on a switch). But yeah, it's of minor importance imho.

**Pull request merged**
