### PR TITLE
Adapt turn order and recalculations of megas to gen 7

### PR DESCRIPTION
**Pull request by coyotte508**
I put some code into functions.

I also fixed a bug with truant & mega in doubles.

And should be correct turn order for megas, with their speed and priority recalculated after megaevolving, and only theirs.

### CODE REVIEW

**Comment by VeteranPadgett** [comment]
Just finished testing. Mega evolution speed and priority are changed after all mega evolutions are done (after loop), instead of one at a time as they evolve (e.g. even if Swampert mega evolves before Charizard-Y it doesn't get the swift swim boost).

Also, you are gonna have to call priority effects again after mega evolving for Sableye and Bannette. On my local version I just reset the priority before calling effects this way:
tmove(i).priority = MoveInfo::SpeedPriority(tmove(i).attack, gen());

**Comment by coyotte508** [comment]
Priority effects should be called just for the megas (`afterMegas` variable to true), but indeed resetting the priorities and removing `afterMegas` is probably better.

Too tired to fix the code today, you can have a go at it if you want.

**Comment by coyotte508** [comment]
@VeteranPadgett Updated the code to take into account calculating speed right after mega-evolving. For the priority thing, I thought that my previous code worked, if it didn't, the new one doesn't either.

**Comment by VeteranPadgett** [comment]
It worked before, I misread the code and thought you were calculating speed during the mega evolution phase. Recalculating the speed when both mega are done is the right way and was what I was trying to say. The only thing to change is that secondPriority shouldn't be recalculated. If you change your code back I can make a pr to this branch to take care of that.

**Comment by coyotte508** [comment]
@VeteranPadgett  Reverted the code.

But I don't understand why second priority shouldn't be recalculated, I need to do it anyway because the speeds were updated.

Also

```cpp
                if (gen() <= 6 || (afterMegas == choice(i).mega())) {
                    callaeffects(i, i, "PriorityChoice");
                }
```

The `(afterMegas == choice(i).mega())` will call this code (the abilitychoice's priority thing) only for the non-megaing pokemon the first time, and only for the megaing pokemon the second time. So the priority for Sableye is fine I think. Prankster is not taken into account the first time, and the second time, it's the ability of Mega-Sableye.

For `Stall`, I do `turnMemory(player).remove("TurnOrder");` in `calculateFinalOrder` so Banette's former Stall effect is removed after it mega-evolved.

All this according to @CTCC1 's comment in the other PR.

**Comment by VeteranPadgett** [comment]
Stall effect isn't removed

**Comment by VeteranPadgett** [comment]
Everything else is fine, sorry for causing you the extra hassle

**Comment by coyotte508** [comment]
@VeteranPadgett sorry, checked the info and seems it's sableye that has stall.

So if it has stall before mega evo, it should keep being last even after mega evolving?

**Comment by VeteranPadgett** [comment]
Yep, stall moves last and prankster moves first.

**Pull request merged**
