### PR TITLE
Hidden Power

### PR DESCRIPTION
**Pull request by VeteranPadgett**
Bottle Caps don't actually change the IV of a Pokemon, but just changes their stats to what it would be with 31 IV. This means a Pokemon can have the stats of all 31 IVs but with any Hidden Power type! The implementation I did lets you pick whatever hp type in teambuilder and then validate that type (if an IV is less than 31 then no bottle cap was used).

Also, gen 7 legendaries must have at least 3 of their IVs equal to 31 similar to gen 6.

### CODE REVIEW

**Comment by VeteranPadgett** [comment]
Added the version control checks. I don't see why we need to send the original IVs though. Unless a new move is released that is directly affected by IVs, our only use for them is to calculate the Hidden Power type.

**Comment by VeteranPadgett** [comment]
Adding more stuff like the sleep talk fix to this branch so you can just pull all of my changes at once. If you want to hold off on the Hidden Power changes though I can add the other stuff to a different PR.

**Comment by Fuzzysqurl** [comment]
Just add as much as you want. ill merge tomorrow just so I can work off what you have too without having to mess around much

**Comment by VeteranPadgett** [comment]
Shell Trap works now but the turn order is wrong. Right now it goes Body Slam->activates Shell Trap->Body Slam paralysis. Probably should have the paralysis and a full para check come before Shell Trap triggers. Also need to figure out when Shell Trap activates in a multi-hit move.

**Comment by coyotte508** [comment]
```cpp
            if (gen() >= 5 && !koed(target) && !hasSubstitute(target)) {
                callaeffects(target, player, "AfterBeingPlumetted");
            }
```
In `BattleSituation::useAttack`. If `ShellTrap` goes after all the hits of a multi-hit move (probably), then you can just add `calleffects(target, player, "AfterBeingPlumetted");` here and use that for shell trap?

**Comment by turbedi** [comment]
Bottle Caps are only working on Lv 100 pokemon according to many sources. Did you take that into account?

**Comment by VeteranPadgett** [comment]
Ok. I still have to test the multi-hit ingame, but I'll try that if needed. Thanks!

For bottle caps, I figured there didn't need to be a level check since all of our tiers are Lv 100. The only exception is LC which I added a check for. For "ingame tiers" like VGC, the Pokemon are autoleveled down so technically Lv 100 pokes are allowed.

**Comment by coyotte508** [comment]
What does an ability like Corrosion have to do with Rocky helmet and Cursed-type moves?

**Comment by VeteranPadgett** [comment]
The Disguise fix affected Corrosion too because they both used turn["BlockDamageOnly"]. Corrosion was coded to make attacks become Curse type against steel and poison pokemon so that poison chance can happen. I used that to determine cases of Corrosion instead of Disguise. I may check in game if poison attacks on a steel pokemon can activate rocky helmet, but the original fix was just intended for Disguise.

**Comment by VeteranPadgett** [comment]
abilities.cpp L:3285

**Comment by coyotte508** [comment]
Well, yea, the corrosion "hack" thing will need to be changed. I will fix it so it doesn't change the type of the move to `Curse`, so can you not protect against it anywhere else in the code?

**Comment by coyotte508** [comment]
For example `Sludge Wave` is a multi target move, if a pokemon with `Corrosion` uses it and it targets first a poison pokemon, then the type becomes `Curse`, and if hitting a grass pokemon next it won't be super effective...

**Comment by Fuzzysqurl** [comment]
Meh. Doubles always ruins life.

**Comment by coyotte508** [comment]
Actually there's a way to deal with Corrosion once and for all.

In `MoveTypeModifier`, if the move is `OffensiveStatusMove` and the opponent is poison/steel, set the power of the move to 0 (set it back after the target has ended, with a callback by adding a turn function `AttackSomehowFailed`), for doubles.

As an added bonus, `BlockDamageOnly` is no longer used by Corrosion. And the type of the move is never set to be curse.

**Comment by VeteranPadgett** [comment]
Ok moved rocky helmet and shell trap

**Pull request merged**
