### PR TITLE
Damage calc fixes

### PR DESCRIPTION
**Pull request by turbedi**
1. Fix calculation with Choice Band/Choice Specs
2. Fix Technician calculation with BP = 60

### CODE REVIEW

**Comment by turbedi** [comment]
No idea where these commits come from or how to remove them :x

**Comment by coyotte508** [comment]
When pulling, you can do `git pull --rebase` instead.

**Comment by turbedi** [comment]
Will try it next time. Is there a way to remove the commits after I have made the PR, should I open a new one with 1 commit or should I leave it as it is?

**Comment by coyotte508** [comment]
You can do git push --force in the same branch

**Comment by turbedi** [comment]
It says that "Everything is up-to-date" and nothing changes

**Comment by coyotte508** [comment]
http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

then git push --force.

In the future when merging with a remote repo do git pull --rebase.

**Comment by turbedi** [comment]
I hate Github... Now I have 1 commit, but everything is messed up. Will try to fix it tomorrow, I am too pissed right now

**Comment by Fuzzysqurl** [comment]
welcome to github. shotguns are on the left to blow your brains out. tequila is on the right to drink them out

**Comment by Fuzzysqurl** [comment]
applied in 5ea4ed72

**Pull request closed without merging**
