### PR TITLE
Make rated battle use a shorter timer

### PR DESCRIPTION
**Pull request by coyotte508**
Rated battles will use a 3 minute timer now.

To review.

### CODE REVIEW

**Comment by Fuzzysqurl** [comment]
The UI is off for the opponent but otherwise it works.
OBW: The bar isn't the correct percentage full for the opponent


NBW: No screenshot but the hover tooltip for the opponent says 5 minutes and the bar is full. The moment. The bar is always the correct percentage full though.

Requires a client update otherwise the timer looks weird as well.

**Comment by coyotte508** [comment]
Added some fixes. Btw only behavior of new client on both new & old servers is relevant, nothing can be done for old clients.

**Comment by turbedi** [comment]
Any update on this?
And when this PR gets merged, Android Client and webclient will need an update too, right?

**Comment by Fuzzysqurl** [comment]
Pull it and check it make sure it works @turbedi 
Double check to make sure no mistakes/etc.

**Comment by turbedi** [comment]
Whoops, completely forgot about this PR. Gonna test it soon™

**Comment by coyotte508** [comment]
why not merge now?

**Comment by Fuzzysqurl** [comment]
Because if we need to restart server for anything else then it gets applied. Plus idk if the 2nd commit ever got tested

**Pull request merged**
